import type { Metadata } from "next";
import AuthComponent from "../AuthComponent";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-sky-50 h-[100vh] flex flex-row justify-center items-center">
      <AuthComponent pageType="login" />
      {children}
    </div>

  );
}
